spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/todoapp}
  security:
    jwt:
      secret: ${JWT_SECRET:defaultSecret}
      expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    root: WARN
    com.todo: INFO